### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by amitkumar-y** [tolik518/SoG_SGreader#18]
**Is your feature request related to a problem? Please describe.**
For new users who want to contribute to any open-source project, it becomes difficult to start when they are not aware of the basic steps. Having a file that describes the initial steps will be helpful for them.

**Describe the solution you'd like**
I suggest adding a contributing.md file to the project. You can assign this task to me, and I will create the file

**Comment by tolik518** [comment]
It sounds like the same issue as #13, doesn't it?
