### ISSUE TITLE
Located Game Patch: 0.99f

### ISSUE THREAD

**Issue by Wingi91** [tolik518/SoG_SGreader#27]
"Located Game Patch: 0.99f
Please open an issue on Github or contact me. There is a mismatch between the supported patch and game patch which could lead to potential data loss."

i hope its fine that i just opened a new issue.

**Comment by tolik518** [comment]
Thanks for the issue, @Wingi91 
Could you provide me the whole log? You can redact your name from the log of course

**Comment by Wingi91** [comment]
with log you mean the json file?

**Comment by tolik518** [comment]
@Wingi91 I mean the output you get in the little green windows where you saw the message :)
You can copy everything with <kbd>ctrl</kbd> + <kbd>a</kbd> and then copy it

**Comment by Wingi91** [comment]
Official Repository: https://github.com/tolik518/SoG_SGreader 
C:\Users\user\AppData\Roaming\Secrets of Grindea\Characters\0.cha
Filesize: 9572
Gender: 1
Nickname: Wingi
InventorySize: 459
ItemCountMerchant: 51
CardsCount: 41
TreasureMapCount: 9
UnknownCount: 9
SkillCount: 44
Level: 85
Cash: 1264
PetsCount: 4
0. Petname: Rabby
1. Petname: Chicken
2. Petname: Slimy
3. Petname: Jumpkin
QuestsCount: 51
EnemiesMetCount: 109
UnknownVariable02Count: 64
RobinBowHighscore: 10350
UnknownVariable03Count: 10
ItemsMetCount: 277
ItemsCraftedCount: 40
FishiesCaughtCount: 30
KilledEnemiesCount: 72
PotionsMax: 3
PotionsEquipped: 3
Birthday: 7.5.1081
PlayTimeTotal: 64,29 hours
Unknownstring: archie
Unknownstring: CalculusDifficulty
Unknownstring: lmb
Unknownstring: tpsc
FlagsCount: 3
HouseStylesCount: 1
Length: 9572
Position: 9572
Is Position and length the same?: True

OS: Windows
Game data folder located: d:/programme/steam\steamapps\common\SecretsOfGrindea
lxNotes.Count: 138
Located Game Patch: 0.99f
Please open an issue on Github or contact me. There is a mismatch between the supported patch and game patch which could lead to potential data loss.

**Comment by tolik518** [comment]
@Wingi91 oh yeah, it looks like you use an slightly older version of the Editor. Just get the most current version and then there should be no issue
